### ISSUE TITLE
TypeError: 'NoneType' object is not iterable

### ISSUE THREAD

**Issue by normwarren** [Stevedow99/dbt-cloud-cancel-running-ci-job-action#11]
The github action failed on pull_request with this error: 
TypeError: 'NoneType' object is not iterable 

Most recent callback: 

```
Traceback (most recent call last):
  File "/app/main.py", line 223, in <module>
    main()
  File "/app/main.py", line 159, in main
    most_recent_runs = get_recent_runs_for_job(base_url=base_dbt_cloud_api_url, headers=req_auth_headers, job_id=dbt_cloud_job_id, same_branch_flag=same_branch_flag, max_runs=max_runs)
  File "/app/main.py", line [12](https://github.com/trainual/trainual-data-dbt/actions/runs/4724221958/jobs/8381167543#step:3:13)3, in get_recent_runs_for_job
    recent_runs_info = extract_dbt_runs_info(recent_runs['data'], same_branch_flag)
  File "/app/main.py", line 68, in extract_dbt_runs_info
    for run in recent_runs_list:
TypeError: 'NoneType' object is not iterable
```
Questions: 
how would I troubleshoot or set to not run when this error, related[ to this](https://rollbar.com/blog/python-typeerror-nonetype-object-is-not-iterable/#:~:text=The%20Python%20TypeError%3A%20NoneType%20Object%20Is%20Not%20Iterable%20error%20can,over%2C%20which%20avoids%20the%20error.), is encountered?

**Comment by Stevedow99** [comment]
Hey @normwarren!

A couple things I would make sure of, to kick off trouble shooting:

- make sure that you have the dbt cloud token set and that the token has correct permissions on the given project
  - `dbt_cloud_token: ${{ secrets.DBT_CLOUD_TOKEN }}`
- Make sure you all fill out account id and job id the following in the action yaml as well, example below:
  - `dbt_cloud_account_id: 12345`
  - `dbt_cloud_job_id: 130247`

The `NoneType` error on this action tends to happen when it's trying to parse through the dbt Cloud API results but the results from dbt Cloud came back an error usually due to permissions

**Comment by normwarren** [comment]
Met with Steve and mentioned we had a team member left when github action broke. We created an access account in dbt-cloud and update the github secrets, and everything worked again ! Thank you Steve!
